insert into reserva (id, nome, tipo, telefone) values (1, 'Fulano', 'Casamento', '1234-1234')
insert into reserva (id, nome, tipo, telefone) values (2, 'Beltrano', 'Formatura', '9876-5432')
insert into reserva (id, nome, tipo, telefone) values (3, 'Sicrano', 'Aniversário', '3334-2234')
insert into reserva (id, nome, tipo, telefone) values (4, 'Asdrubal', 'Aniversário', '1275-4145')
insert into reserva (id, nome, tipo, telefone) values (5, 'Diogo Hugo', 'Formatura', '9002-8922')